version: '3.8'
services:
  bend:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DO_PULL=true
    container_name: bend
    ports:
      - "9999:9999"
    environment:
      - NAME=bend
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
