name: Check for new crates
on:
  schedule:
    - cron: "13,43 * * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHA_HVMBEND_COMMIT_CHECK }}
      - name: Fetch latest HVM commit checksum from GitHub API
        run: |
          curl -sLC - https://crates.io/api/v1/crates/hvm | \
          jq '.crate.max_stable_version, .crate.max_version' > stable/crates_io_hvm.txt
      - name: Fetch latest Bend commit checksum from GitHub API
        run: |
          curl -sLC - https://crates.io/api/v1/crates/bend-lang | \
          jq '.crate.max_stable_version, .crate.max_version' > stable/crates_io_bend-lang.txt
      - name: Fail early in case of API null response
        if: ${{ github.status == 'success' }}
        run: |
          if grep -qE '^null$' stable/crates_io_hvm.txt stable/crates_io_bend-lang.txt; then
            exit 1
          fi
      - name: Check if latest commit checksums changed
        run: echo "modified=$([[ -z `git status --porcelain` ]] && echo false || echo true)" >> $GITHUB_ENV
      - name: Commit the latest commit checksums
        if: ${{ env.modified }} == "true"
        run: |
          git config --global user.name 'Wolfsauge'
          git config --global user.email 'no@email'
          git commit -am "New crates discovered"
          git push
