name: Check for new commits
on:
  schedule:
    - cron:  "23,53 * * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHA_HVMBEND_COMMIT_CHECK }}
      - name: Fetch latest HVM commit checksum from GitHub API
        run: |
          curl -sL https://api.github.com/repos/HigherOrderCO/HVM/commits | \
          jq ".[0] | .sha" > hvm-latest-commit-sha.txt
      - name: Fetch latest Bend commit checksum from GitHub API
        run: |
          curl -sL https://api.github.com/repos/HigherOrderCO/Bend/commits | \
          jq ".[0] | .sha" > bend-latest-commit-sha.txt
      - name: Fail early in case of API null response
        if: ${{ github.status == 'success' }}
        run: |
          if grep -qE '^null$' hvm-latest-commit-sha.txt bend-latest-commit-sha.txt; then
            exit 1
          fi
      - name: Check if latest commit checksums changed
        run: echo "modified=$([[ -z `git status --porcelain` ]] && echo false || echo true)" >> $GITHUB_ENV
      - name: Commit the latest commit checksums
        if: ${{ env.modified }} == "true"
        run: |
          git config --global user.name 'Wolfsauge'
          git config --global user.email 'no@email'
          git commit -am "New commit checksum discovered"
          git push
