name: stable:Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "stable/crates_io_*.txt"
      - "stable/Dockerfile"

env:
  IMAGE_NAME: nschle/bend
  BASE_IMAGE: 12.4.1-runtime-ubuntu22.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: stable

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: stable/Dockerfile
          provenance: mode=max
          sbom: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BASE_IMAGE }}-stable
          push: true
